services:
  # API 服务
  api:
    build: .
    container_name: apiwong-api
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./configs:/root/configs
      - ./logs:/root/logs
    restart: unless-stopped
    networks:
      - apiwong-network